name:                chameleon
version:             0.1.0.0
github:              "maybetonyfu/chameleon"
license:             BSD3
author:              "Tony Fu"
maintainer:          "tonyfu@fastmail.com"
copyright:           "2021 Tony Fu"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub

dependencies:
- base >= 4.14 && < 4.17
- aeson
- process
- array
- base
- bytestring
- containers
- ghc
- ghc-paths
- ghc-lib-parser
- haskell-src-exts
- transformers
- Agda
- scotty
- string-qq
- lens
- text
- filepath
- directory
- parsec
- silently
- hlint
- ghc
- split
- exceptions
- regex-compat

library:
  source-dirs: src

executables:
  chameleon:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chameleon

